/*
 * Copyright (c) 2023, Quincy.W <wangqyfm@foxmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_APM32_CLOCK_F4_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_APM32_CLOCK_F4_H_

#include "apm32_clock.h"

#define APM32_AHB1PCLKEN_OFFSET 0x30
#define APM32_AHB2PCLKEN_OFFSET 0x34
#define APM32_AHB3PCLKEN_OFFSET 0x38
#define APM32_APB1PCLKEN_OFFSET 0x40
#define APM32_APB2PCLKEN_OFFSET 0x44
#define APM32_BDCTRL_OFFSET     0x70

/// BDCTRL
#define APM32_CLOCK_RTC        APM32_RCM_FIELD_DEF_OFFSET(APM32_BDCTRL_OFFSET, 15)     // RCM_BDCTRL.15 

/// AHB1
#define APM32_CLOCK_GPIOA      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 0)  // RCM_AHB1PCLKEN.0
#define APM32_CLOCK_GPIOB      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 1)  // RCM_AHB1PCLKEN.1
#define APM32_CLOCK_GPIOC      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 2)  // RCM_AHB1PCLKEN.2
#define APM32_CLOCK_GPIOD      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 3)  // RCM_AHB1PCLKEN.3
#define APM32_CLOCK_GPIOE      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 4)  // RCM_AHB1PCLKEN.4
#define APM32_CLOCK_GPIOF      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 5)  // RCM_AHB1PCLKEN.5
#define APM32_CLOCK_GPIOG      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 6)  // RCM_AHB1PCLKEN.6
#define APM32_CLOCK_GPIOH      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 7)  // RCM_AHB1PCLKEN.7
#define APM32_CLOCK_GPIOI      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 8)  // RCM_AHB1PCLKEN.8
                                                                                       // RCM_AHB1PCLKEN.9, res
                                                                                       // RCM_AHB1PCLKEN.10, res
                                                                                       // RCM_AHB1PCLKEN.11, res
#define APM32_CLOCK_CRC        APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 12) // RCM_AHB1PCLKEN.12
                                                                                       // RCM_AHB1PCLKEN.13, res
                                                                                       // RCM_AHB1PCLKEN.14, res
                                                                                       // RCM_AHB1PCLKEN.15, res
                                                                                       // RCM_AHB1PCLKEN.16, res
                                                                                       // RCM_AHB1PCLKEN.17, res
#define APM32_CLOCK_BAKPSRAM   APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 18) // RCM_AHB1PCLKEN.18
                                                                                       // RCM_AHB1PCLKEN.19
#define APM32_CLOCK_DRAM       APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 20) // RCM_AHB1PCLKEN.20
#define APM32_CLOCK_DMA1       APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 21) // RCM_AHB1PCLKEN.21
#define APM32_CLOCK_DMA2       APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 22) // RCM_AHB1PCLKEN.22
                                                                                       // RCM_AHB1PCLKEN.23, res
                                                                                       // RCM_AHB1PCLKEN.24, res
#define APM32_CLOCK_ETH        APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 25) // RCM_AHB1PCLKEN.25
#define APM32_CLOCK_ETHTX      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 26) // RCM_AHB1PCLKEN.26
#define APM32_CLOCK_ETHRX      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 27) // RCM_AHB1PCLKEN.27
#define APM32_CLOCK_ETHPTP     APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 28) // RCM_AHB1PCLKEN.28
#define APM32_CLOCK_OTGHS1     APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 29) // RCM_AHB1PCLKEN.29
#define APM32_CLOCK_HSULPI     APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB1PCLKEN_OFFSET, 30) // RCM_AHB1PCLKEN.30
                                                                                       // RCM_AHB1PCLKEN.31, res

/// AHB2
#define APM32_CLOCK_DCI        APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 0)  // RCM_AHB2PCLKEN.0
#define APM32_CLOCK_FPU        APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 1)  // RCM_AHB2PCLKEN.1
#define APM32_CLOCK_BN         APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 2)  // RCM_AHB2PCLKEN.2
#define APM32_CLOCK_SM         APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 3)  // RCM_AHB2PCLKEN.3
#define APM32_CLOCK_CRYP       APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 4)  // RCM_AHB2PCLKEN.4
#define APM32_CLOCK_HASHP      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 5)  // RCM_AHB2PCLKEN.5
#define APM32_CLOCK_RNG        APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 6)  // RCM_AHB2PCLKEN.6
#define APM32_CLOCK_OTGFS      APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB2PCLKEN_OFFSET, 7)  // RCM_AHB2PCLKEN.7

/// AHB3
#define APM32_CLOCK_EMMC       APM32_RCM_FIELD_DEF_OFFSET(APM32_AHB3PCLKEN_OFFSET, 0)  // RCM_AHB3PCLKEN.0
                                                                                       // RCM_AHB3PCLKEN[30:1], res

/// APB1
#define APM32_CLOCK_TMR2       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 0)  // RCM_APB1PCLKEN.0
#define APM32_CLOCK_TMR3       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 1)  // RCM_APB1PCLKEN.1
#define APM32_CLOCK_TMR4       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 2)  // RCM_APB1PCLKEN.2
#define APM32_CLOCK_TMR5       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 3)  // RCM_APB1PCLKEN.3
#define APM32_CLOCK_TMR6       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 4)  // RCM_APB1PCLKEN.4
#define APM32_CLOCK_TMR7       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 5)  // RCM_APB1PCLKEN.5
#define APM32_CLOCK_TMR12      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 6)  // RCM_APB1PCLKEN.6
#define APM32_CLOCK_TMR13      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 7)  // RCM_APB1PCLKEN.7
#define APM32_CLOCK_TMR14      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 8)  // RCM_APB1PCLKEN.8
                                                                                       // RCM_APB1PCLKEN.9, res
                                                                                       // RCM_APB1PCLKEN.10, res
#define APM32_CLOCK_WWDT       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 11) // RCM_APB1PCLKEN.11
#define APM32_CLOCK_SPI2       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 14) // RCM_APB1PCLKEN.14
#define APM32_CLOCK_SPI3       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 15) // RCM_APB1PCLKEN.15
#define APM32_CLOCK_USART2     APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 17) // RCM_APB1PCLKEN.17
#define APM32_CLOCK_USART3     APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 18) // RCM_APB1PCLKEN.18
#define APM32_CLOCK_UART4      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 19) // RCM_APB1PCLKEN.19
#define APM32_CLOCK_UART5      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 20) // RCM_APB1PCLKEN.20
#define APM32_CLOCK_I2C1       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 21) // RCM_APB1PCLKEN.21
#define APM32_CLOCK_I2C2       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 22) // RCM_APB1PCLKEN.22
#define APM32_CLOCK_I2C3       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 23) // RCM_APB1PCLKEN.23
#define APM32_CLOCK_CAN1       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 25) // RCM_APB1PCLKEN.25
#define APM32_CLOCK_CAN2       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 26) // RCM_APB1PCLKEN.26
#define APM32_CLOCK_PMU        APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 28) // RCM_APB1PCLKEN.28
#define APM32_CLOCK_DAC        APM32_RCM_FIELD_DEF_OFFSET(APM32_APB1PCLKEN_OFFSET, 29) // RCM_APB1PCLKEN.29
                                                                                       // RCM_APB1PCLKEN.30, res
                                                                                       // RCM_APB1PCLKEN.31, res

/// APB2
#define APM32_CLOCK_TMR1       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 0)  // RCM_APB2PCLKEN.0
#define APM32_CLOCK_TMR8       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 1)  // RCM_APB2PCLKEN.1
                                                                                       // RCM_APB2PCLKEN.2, res
                                                                                       // RCM_APB2PCLKEN.3, res
#define APM32_CLOCK_USART1     APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 4)  // RCM_APB2PCLKEN.4
#define APM32_CLOCK_USART6     APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 5)  // RCM_APB2PCLKEN.5
                                                                                       // RCM_APB2PCLKEN.6, res
                                                                                       // RCM_APB2PCLKEN.7, res
#define APM32_CLOCK_ADC1       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 8)  // RCM_APB2PCLKEN.8
#define APM32_CLOCK_ADC2       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 9)  // RCM_APB2PCLKEN.9
#define APM32_CLOCK_ADC3       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 10) // RCM_APB2PCLKEN.10
#define APM32_CLOCK_SDIO       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 11) // RCM_APB2PCLKEN.11
#define APM32_CLOCK_SPI1       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 12) // RCM_APB2PCLKEN.12
#define APM32_CLOCK_SPI4       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 13) // RCM_APB2PCLKEN.13
#define APM32_CLOCK_SYSCFG     APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 14) // RCM_APB2PCLKEN.14
#define APM32_CLOCK_TMR9       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 16) // RCM_APB2PCLKEN.16
#define APM32_CLOCK_TMR10      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 17) // RCM_APB2PCLKEN.17
#define APM32_CLOCK_TMR11      APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 18) // RCM_APB2PCLKEN.18
                                                                                       // RCM_APB2PCLKEN.19, res
#define APM32_CLOCK_SPI5       APM32_RCM_FIELD_DEF_OFFSET(APM32_APB2PCLKEN_OFFSET, 20) // RCM_APB2PCLKEN.20
                                                                                       // RCM_APB2PCLKEN[31:21], res
#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_APM32_CLOCK_F4_H_ */
